// <auto-generated />
using System;
using GreenHaven.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GreenHaven.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251204130110_RemoveRedundantCategories")]
    partial class RemoveRedundantCategories
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GreenHaven.API.Entities.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("GreenHaven.API.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Air Purifying"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Succulents"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Flowering"
                        });
                });

            modelBuilder.Entity("GreenHaven.API.Entities.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("GreenHaven.API.Entities.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("PlantId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("PlantId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("GreenHaven.API.Entities.Plant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Difficulty")
                        .HasColumnType("int");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsPetFriendly")
                        .HasColumnType("bit");

                    b.Property<int>("LightRequirement")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ScientificName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("int");

                    b.Property<int>("WaterNeeds")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Plants");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Description = "A hardy plant that thrives in low light.",
                            Difficulty = 0,
                            ImageUrl = "/SnakePlant.png",
                            IsPetFriendly = false,
                            LightRequirement = 0,
                            Name = "Snake Plant",
                            Price = 499.00m,
                            ScientificName = "Sansevieria trifasciata",
                            StockQuantity = 50,
                            WaterNeeds = 0
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            Description = "Easy to grow and produces babies.",
                            Difficulty = 0,
                            ImageUrl = "/SpiderPlant.png",
                            IsPetFriendly = true,
                            LightRequirement = 1,
                            Name = "Spider Plant",
                            Price = 399.00m,
                            ScientificName = "Chlorophytum comosum",
                            StockQuantity = 30,
                            WaterNeeds = 1
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 1,
                            Description = "Famous for its natural leaf holes.",
                            Difficulty = 0,
                            ImageUrl = "/Monstera.png",
                            IsPetFriendly = false,
                            LightRequirement = 1,
                            Name = "Monstera Deliciosa",
                            Price = 1299.00m,
                            ScientificName = "Monstera deliciosa",
                            StockQuantity = 20,
                            WaterNeeds = 1
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 1,
                            Description = "Popular indoor tree with large leaves.",
                            Difficulty = 2,
                            ImageUrl = "/FiddleLeaf.png",
                            IsPetFriendly = false,
                            LightRequirement = 2,
                            Name = "Fiddle Leaf Fig",
                            Price = 2499.00m,
                            ScientificName = "Ficus lyrata",
                            StockQuantity = 15,
                            WaterNeeds = 1
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 5,
                            Description = "Beautiful white flowers and air purifying.",
                            Difficulty = 0,
                            ImageUrl = "/PeaceLily.png",
                            IsPetFriendly = false,
                            LightRequirement = 0,
                            Name = "Peace Lily",
                            Price = 699.00m,
                            ScientificName = "Spathiphyllum",
                            StockQuantity = 40,
                            WaterNeeds = 2
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 1,
                            Description = "Shiny, dark leaves.",
                            Difficulty = 0,
                            ImageUrl = "/RubberPlant.png",
                            IsPetFriendly = false,
                            LightRequirement = 1,
                            Name = "Rubber Plant",
                            Price = 899.00m,
                            ScientificName = "Ficus elastica",
                            StockQuantity = 25,
                            WaterNeeds = 1
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 4,
                            Description = "Medicinal succulent.",
                            Difficulty = 0,
                            ImageUrl = "/AloeVera.png",
                            IsPetFriendly = false,
                            LightRequirement = 2,
                            Name = "Aloe Vera",
                            Price = 299.00m,
                            ScientificName = "Aloe barbadensis miller",
                            StockQuantity = 60,
                            WaterNeeds = 0
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 1,
                            Description = "Fast growing trailing vine.",
                            Difficulty = 0,
                            ImageUrl = "/Pothos.png",
                            IsPetFriendly = false,
                            LightRequirement = 0,
                            Name = "Golden Pothos",
                            Price = 349.00m,
                            ScientificName = "Epipremnum aureum",
                            StockQuantity = 55,
                            WaterNeeds = 1
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 1,
                            Description = "Extremely drought tolerant.",
                            Difficulty = 0,
                            ImageUrl = "/ZZPlant.png",
                            IsPetFriendly = false,
                            LightRequirement = 0,
                            Name = "ZZ Plant",
                            Price = 799.00m,
                            ScientificName = "Zamioculcas zamiifolia",
                            StockQuantity = 35,
                            WaterNeeds = 0
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 5,
                            Description = "Tropical flair with large leaves.",
                            Difficulty = 1,
                            ImageUrl = "/Monstera.png",
                            IsPetFriendly = false,
                            LightRequirement = 2,
                            Name = "Bird of Paradise",
                            Price = 1899.00m,
                            ScientificName = "Strelitzia nicolai",
                            StockQuantity = 10,
                            WaterNeeds = 2
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 1,
                            Description = "Classic trailing plant.",
                            Difficulty = 1,
                            ImageUrl = "/Pothos.png",
                            IsPetFriendly = false,
                            LightRequirement = 1,
                            Name = "English Ivy",
                            Price = 399.00m,
                            ScientificName = "Hedera helix",
                            StockQuantity = 45,
                            WaterNeeds = 1
                        },
                        new
                        {
                            Id = 12,
                            CategoryId = 1,
                            Description = "Heart-shaped leaves.",
                            Difficulty = 0,
                            ImageUrl = "/Pothos.png",
                            IsPetFriendly = false,
                            LightRequirement = 1,
                            Name = "Heartleaf Philodendron",
                            Price = 449.00m,
                            ScientificName = "Philodendron hederaceum",
                            StockQuantity = 40,
                            WaterNeeds = 1
                        },
                        new
                        {
                            Id = 13,
                            CategoryId = 4,
                            Description = "Symbol of good luck.",
                            Difficulty = 0,
                            ImageUrl = "/AloeVera.png",
                            IsPetFriendly = false,
                            LightRequirement = 2,
                            Name = "Jade Plant",
                            Price = 599.00m,
                            ScientificName = "Crassula ovata",
                            StockQuantity = 30,
                            WaterNeeds = 0
                        },
                        new
                        {
                            Id = 14,
                            CategoryId = 4,
                            Description = "Unique cascading succulent.",
                            Difficulty = 2,
                            ImageUrl = "/AloeVera.png",
                            IsPetFriendly = false,
                            LightRequirement = 1,
                            Name = "String of Pearls",
                            Price = 649.00m,
                            ScientificName = "Senecio rowleyanus",
                            StockQuantity = 20,
                            WaterNeeds = 0
                        },
                        new
                        {
                            Id = 15,
                            CategoryId = 1,
                            Description = "Pet friendly air purifier.",
                            Difficulty = 0,
                            ImageUrl = "/Monstera.png",
                            IsPetFriendly = true,
                            LightRequirement = 0,
                            Name = "Bamboo Palm",
                            Price = 1499.00m,
                            ScientificName = "Chamaedorea seifrizii",
                            StockQuantity = 15,
                            WaterNeeds = 2
                        },
                        new
                        {
                            Id = 16,
                            CategoryId = 1,
                            Description = "Round, coin-like leaves.",
                            Difficulty = 1,
                            ImageUrl = "/ZZPlant.png",
                            IsPetFriendly = true,
                            LightRequirement = 1,
                            Name = "Chinese Money Plant",
                            Price = 549.00m,
                            ScientificName = "Pilea peperomioides",
                            StockQuantity = 25,
                            WaterNeeds = 1
                        },
                        new
                        {
                            Id = 17,
                            CategoryId = 1,
                            Description = "Leaves fold up at night.",
                            Difficulty = 2,
                            ImageUrl = "/PeaceLily.png",
                            IsPetFriendly = true,
                            LightRequirement = 0,
                            Name = "Calathea Prayer Plant",
                            Price = 999.00m,
                            ScientificName = "Calathea orbifolia",
                            StockQuantity = 18,
                            WaterNeeds = 2
                        },
                        new
                        {
                            Id = 18,
                            CategoryId = 5,
                            Description = "Aromatic and calming.",
                            Difficulty = 1,
                            ImageUrl = "/PeaceLily.png",
                            IsPetFriendly = false,
                            LightRequirement = 2,
                            Name = "Lavender",
                            Price = 399.00m,
                            ScientificName = "Lavandula",
                            StockQuantity = 50,
                            WaterNeeds = 0
                        },
                        new
                        {
                            Id = 19,
                            CategoryId = 1,
                            Description = "Lush and feathery.",
                            Difficulty = 1,
                            ImageUrl = "/SpiderPlant.png",
                            IsPetFriendly = true,
                            LightRequirement = 1,
                            Name = "Boston Fern",
                            Price = 599.00m,
                            ScientificName = "Nephrolepis exaltata",
                            StockQuantity = 30,
                            WaterNeeds = 2
                        },
                        new
                        {
                            Id = 20,
                            CategoryId = 4,
                            Description = "Round and spiky.",
                            Difficulty = 0,
                            ImageUrl = "/AloeVera.png",
                            IsPetFriendly = false,
                            LightRequirement = 2,
                            Name = "Barrel Cactus",
                            Price = 899.00m,
                            ScientificName = "Echinocactus grusonii",
                            StockQuantity = 12,
                            WaterNeeds = 0
                        },
                        new
                        {
                            Id = 21,
                            CategoryId = 5,
                            Description = "Elegant blooming orchid.",
                            Difficulty = 1,
                            ImageUrl = "/PeaceLily.png",
                            IsPetFriendly = true,
                            LightRequirement = 1,
                            Name = "Phalaenopsis Orchid",
                            Price = 1199.00m,
                            ScientificName = "Phalaenopsis",
                            StockQuantity = 20,
                            WaterNeeds = 1
                        },
                        new
                        {
                            Id = 22,
                            CategoryId = 4,
                            Description = "Rosette forming succulent.",
                            Difficulty = 0,
                            ImageUrl = "/AloeVera.png",
                            IsPetFriendly = true,
                            LightRequirement = 2,
                            Name = "Echeveria",
                            Price = 249.00m,
                            ScientificName = "Echeveria elegans",
                            StockQuantity = 40,
                            WaterNeeds = 0
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("GreenHaven.API.Entities.Order", b =>
                {
                    b.HasOne("GreenHaven.API.Entities.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("GreenHaven.API.Entities.OrderItem", b =>
                {
                    b.HasOne("GreenHaven.API.Entities.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GreenHaven.API.Entities.Plant", "Plant")
                        .WithMany()
                        .HasForeignKey("PlantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Plant");
                });

            modelBuilder.Entity("GreenHaven.API.Entities.Plant", b =>
                {
                    b.HasOne("GreenHaven.API.Entities.Category", "Category")
                        .WithMany("Plants")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("GreenHaven.API.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("GreenHaven.API.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GreenHaven.API.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("GreenHaven.API.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GreenHaven.API.Entities.Category", b =>
                {
                    b.Navigation("Plants");
                });

            modelBuilder.Entity("GreenHaven.API.Entities.Order", b =>
                {
                    b.Navigation("OrderItems");
                });
#pragma warning restore 612, 618
        }
    }
}
