// <auto-generated />
using GreenHaven.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GreenHaven.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251203063312_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GreenHaven.API.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Air Purifying"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Low Light"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Pet Friendly"
                        });
                });

            modelBuilder.Entity("GreenHaven.API.Entities.Plant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Difficulty")
                        .HasColumnType("int");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsPetFriendly")
                        .HasColumnType("bit");

                    b.Property<int>("LightRequirement")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ScientificName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("int");

                    b.Property<int>("WaterNeeds")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Plants");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Description = "A hardy plant that thrives in low light.",
                            Difficulty = 0,
                            ImageUrl = "https://placeholder.com/snakeplant.jpg",
                            IsPetFriendly = false,
                            LightRequirement = 0,
                            Name = "Snake Plant",
                            Price = 15.99m,
                            ScientificName = "Sansevieria trifasciata",
                            StockQuantity = 50,
                            WaterNeeds = 0
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 3,
                            Description = "Easy to grow and produces babies.",
                            Difficulty = 0,
                            ImageUrl = "https://placeholder.com/spiderplant.jpg",
                            IsPetFriendly = true,
                            LightRequirement = 1,
                            Name = "Spider Plant",
                            Price = 12.50m,
                            ScientificName = "Chlorophytum comosum",
                            StockQuantity = 30,
                            WaterNeeds = 1
                        });
                });

            modelBuilder.Entity("GreenHaven.API.Entities.Plant", b =>
                {
                    b.HasOne("GreenHaven.API.Entities.Category", "Category")
                        .WithMany("Plants")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("GreenHaven.API.Entities.Category", b =>
                {
                    b.Navigation("Plants");
                });
#pragma warning restore 612, 618
        }
    }
}
